# ResistanceChange by Squidicuz
# Ported from ObsidianDestroyer
# For information visit http://dev.bukkit.org/server-mods/ObsidianDestroyer

# Made with love <3

# Do not touch this line. It will rewrite your config.
Version: ${project.version}

# This will only check for updates. We will never download them for you.
checkupdate: true

# The explosion radius that will affect blocks 
Radius: 3

# The id of the item you use to check durability.
CheckItemId: 38

# [!]Disabling this may result in your server crashing[!]
# Experimental Timer safety. This if you are having issues with your server running out of memory.
# This is not a fix to out of memory errors. Though it can help prevent this plugin from crashing your server.
# "SystemMinMemory" = Minimun amount (MegaBytes) of RAM that can be availabe.
# If there is less than this amount of memory available, no new timer threads will be created.
Threading:
  UseTimerSafety: true
  SystemMinMemory: 80 
  
# false means that water won't protect blocks listed above from explosions.
# This only applies to blocks that are managed by ResistanceChanger
FluidsProtectBlocks: true

# Enables a bypass to allow explosions to affect ALL blocks under / next to liquids.
# This will bypass ALL blocks. We recommend not to use both this AND fluids protect.
Explosions:
  BypassAllFluidProtection: false
  
  # Protects "TNT cannons" from being destroyed when used. 
  # This doesn't do anything unless the above option is true.
  TNTCannonsProtected: true
  
# List of worlds that the plugin will not interact with.
# Example: DisabledOnWorlds: [world_survival, world_creative]
DisabledOnWorlds: []

#List of Blocks to apply a resistance/durability to
HandledBlocks:
  # Name of block that will have durability applied
  Stone:
    # Id of the block. This must be a block
    BlockID: 1
    # Block explosion resistance settings
    Durability:
      # Amount of explosions that it will take to blow up the block
      Amount: 2
      # Enabled??
      Enabled: true
      # Chance to drop. Setting to anything at or above 1 will make them always drop.
      ChanceToDrop: 0.9
      # Wether the durability will reset after some time
      ResetEnabled: false
      # Time for the durability to reset
      ResetAfter: 300000
    # Explosion types you want us to handle.
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: false
      Withers: false
  SmoothBrick:
    BlockID: 98
    Durability:
      Amount: 4
      Enabled: true
      ChanceToDrop: 0.7
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  SmoothBrickStairs:
    BlockID: 109
    Durability:
      Amount: 4
      Enabled: true
      ChanceToDrop: 0.7
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: false
      Withers: false
  NetherBrick:
    BlockID: 112
    Durability:
      Amount: 3
      Enabled: true
      ChanceToDrop: 0.7
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: false
      Withers: false
  NetherBrickStairs:
    BlockID: 114
    Durability:
      Amount: 3
      Enabled: true
      ChanceToDrop: 0.7
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: false
      Withers: false
  Obsidian:
    BlockID: 49
    Durability:
      Amount: 8
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  EnchantmentTable:
    BlockID: 116
    Durability:
      Amount: 6
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  EnderChest:
    BlockID: 130
    Durability5
      Amount: 4
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  Anvil:
    BlockID: 145
    Durability:
      Amount: 3
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: false
      ResetAfter: 300000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  Bedrock:
    BlockID: 7
    Durability:
      Amount: 100
      Enabled: false
      ChanceToDrop: 0.0
      ResetEnabled: false
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
  
# Thats it :3